### ISSUE TITLE
Failed to Install Mail Plug-in

### ISSUE THREAD

**Issue by abdullah-adhami** [rileytestut/AltStore#108]
Failed to Install Mail Plug-in
Archive:  /var/folders/59/8wtpj_7s4n38ck6hsrsdy01w0000gn/T/CFNetworkDownload_F0lp8c.tmp

I keep getting this massage when trying to install altstore on iPhone 11 Pro max 
iOS: 13.3
Mac user

**Comment by shaunvis** [comment]
Similar issue here.

![Screen Shot 2020-02-14 at 4 49 41 PM](https://user-images.githubusercontent.com/4119449/74574709-224f0680-4f4a-11ea-92c2-a00f6d02b202.png)

**Comment by BriteShard** [comment]
I fixed this by installing it manually. Go to [https://github.com/rileytestut/AltStore/tree/master/AltServer](url) and download AltPlugin.mailbundle.zip. Save it to your downloads folder(Don't expand it, just save the file). Next, go back through the link and open InstallPlugin.sh. Copy this text. Open a terminal, go to your Downloads folder, and type sudo su (This will give you the permissions you need to run the code). Finally, close Mail if it is open, open it again, hit command-comma(Open up settings for it), and hit manage plugins. Enable the plugin.

Sorry if I am not very clear... hopefully this helps. Worked for me.

**Comment by shaunvis** [comment]
Thanks, worked for me.

**Comment by noah978** [comment]
I'll consider this issue resolved then.

**Comment by gurazeez07** [comment]
hey I am trying the same thing. the plug in shows it was installed but doesn't show in the manage plug-ins section. I've followed your instructions and many more from the internet still doesn't seem to work. also when I type the command it says command not found, can you help?

**Comment by Tdhampson** [comment]
@gurazeez07 I have the exact same problem. I wonder if it was some sort of new patch. Does anyone know a workaround?

**Comment by Tdhampson** [comment]
Some more information: I did what you said--- I downloaded the zip file and pasted that code into terminal, but terminal returned the error: "rm: /Library/Mail/Bundles: is a directory" and the plugin still will not install.
Also @gurazeez07 I found that the reason why the manage plug-ins section doesn't show up is simply because the appvalley mail extension isn't installing, but when you attempt to download another plugin, it should work and show up. Hence, the problem is with getting Appvalley to work, not with mail plugins in general I think

**Comment by BriteShard** [comment]
It looks like there was an update, I can't even find InstallPlugin.sh anymore. It sounds like your plugin isn't appearing in the mail app? You could try following the Compilation Instructions.
