### ISSUE TITLE
Cannot activate more than 3 apps and app extensions.

### ISSUE THREAD

**Issue by LikeSundayLikeRain** [rileytestut/AltStore#132]
Having issue while trying to sideload Cercube 5.1.6, the error message says "Cannot activate more than 3 apps and app extensions."

**Comment by tyl0r** [comment]
I'm having the same issue when trying to load from sources.

**Comment by noah978** [comment]
This is because Cercube has 5 App Extensions and when you install from a source, you aren't given the option to remove them.

However, this was actually due to an iOS issue where it counted App Extensions against the 3 app limit. But the bug was recently fixed so if you update to iOS 13.5, you should no longer experience this issue,

I'll consider this one closed.
