### ISSUE TITLE
Reached limit of 3 apps per device, doesn’t stop when I delete one

### ISSUE THREAD

**Issue by CrCrate** [rileytestut/AltStore#136]
I want to install another app but I can’t bc error above, I tried deleting and app and completely reinstalling altstore/server and nothing worked

**Comment by supremethememe** [comment]
Sorry about this, it’s because of Apple’s stupid free developer program. Apple really needs to make it more friendly for people who don’t feel like paying $99 a year for a developer profile.

**Comment by CrCrate** [comment]
I know that. Deleting an app is supposed to free a slot.

**Comment by nighto** [comment]
Hit that problem when tried to install Provenance beta after having three
apps (AltStore beta, Delta beta and Popcorn Time); removing PT didn't free
a slot. In the end, apparently the problem was with Provenance beta because
the regular version installed and activated without any issues.

[]s
Arlindo Pereira


Em sex., 27 de mar. de 2020 às 15:32, supremethememe <
notifications@github.com> escreveu:

**Comment by noah978** [comment]
This issue should be fixed in the latest versions of AltServer and AltStore. If any issues persist, please leave a comment below. Closing this issue.
