### ISSUE TITLE
"Refresh All" bricked Delta

### ISSUE THREAD

**Issue by OopaPop** [rileytestut/AltStore#143]
Hello.

I have AltStore and Delta.

When I clicked "Refresh All" in the "My Apps" section, it started refreshing both programs at the same time. Then, AltStore finished refreshing sooner, and quit (which is normal). But coming back, Delta doesn't open, respond, or refresh anymore, since AltStore quit in the middle of Delta's refresh progress. I don't kniw what to do anymore, Delta doesn't refresh anymore, and doesn't respond, but I have many important roms on it, and don't want to lose them. What should I do?

As for the bug, it is very easily fixable. When a user clicks "Refresh All", don't refresh AltStore before all other programs have finished completely refreshing. If it is unable to, give an error message, but stop AltStore refreshing so it doesn't quit and brick all the programs.

**Update**: Thankfully, I had turned on Sync to Google Drive before Delta crashing. So I deleted Delta, reinstalled it, logged in to my synced account, and everything was there. However, I think this should still be fixed.

P.S. love your work! Delta is amazing, and the best emulator not only for iOS, but for all platforms!!!! What's the point of playing Game Boy games on a computer, when a Game Boy is supposed to be very portable? :D

**Comment by noah978** [comment]
Not sure how we can reproduce this bug since the expected behavior is AltStore will wait for all other apps to finish first, then complete it's own refresh. Luckily this is not a huge issue since due to fairly recent updates, AltStore no longer needs to close when refreshing, only when updating.

I'll consider this issue closed, but if you somehow still have this issue after updating to the latest versions of AltStore and AltServer, please leave a comment below.
