### ISSUE TITLE
Support for Itunes from the Microsoft Store

### ISSUE THREAD

**Issue by Samuel12321** [rileytestut/AltStore#147]
The Microsoft store version is the more publicly distributed version of iTunes for windows. As such it seems restricting that it isn't supported.

**Comment by C0braD3v** [comment]
Actually, this is not true. You can download iTunes without the MS store, they have an MSI. Please close this issue.

**Comment by Samuel12321** [comment]
Apologies, i found the msi version.
However i still think support for the store version would be a good improvement.

**Comment by C0braD3v** [comment]
I do agree, however I’m sure Riley has considered this and I’m sure that the store version has limitations (due to the way it’s installed, where app data is stores, or another factor. I’m not an iOS developer and don’t have experience with this type of development so I’m not certain) and so he probably is not able to do so at this time.

**Comment by noah978** [comment]
Unfortunately, supporting the MS Store version of iTunes is not possible at this time. AltServer requires various functions included with the installation of iTunes that are simply not accessible using the MS Store version of iTunes. I will be closing this issue.
