### ISSUE TITLE
Not a Number

### ISSUE THREAD

**Issue by Alphaltz** [rileytestut/AltStore#166]
When typing in your username and password and pressing install with itunes open it says Installation failed not a number

**Comment by Ry3yr** [comment]
Same here.
OS: Windows 10
Installed: iTunes (latest) + iCloud (logged in)
   -> Status: both running

Alt server keeps returning "not a number error"

Measures taken sofar:
Deleted "C:\ProgramData\Apple Computer\iTunes\adi"
as Altserver refused to work due to access problems to files inside the folder

Measures here:
https://altstore.io/faq/
have proven ineffective...

**Comment by noah978** [comment]
This issue should be fixed on the [latest version of Altserver Beta.](https://altstore.io/altserver/beta) Closing this issue. If the issue persists, leave a comment below.

**Comment by Alphaltz** [comment]
Still happens

**Comment by Smart-Electron** [comment]
![notanumber](https://user-images.githubusercontent.com/64767383/82765018-1afc8c00-9dc8-11ea-8a7f-4c81a0598418.png)
