### ISSUE TITLE
invalid app 

### ISSUE THREAD

**Issue by archicated** [rileytestut/AltStore#187]
90% of the apps i try to download are all invalid when i load them into the altstore , fix this please.

**Comment by noah978** [comment]
Need more information:
* What iOS version?
* Which specific IPAs?
* Windows or Mac?

**Comment by reach4bawer** [comment]
I am facing the same problem. I am on  my ipad running iOS 13.5, had the same problem for 13.4. My ALT server is running on MacOs . 
The IPA that I tried the following apps from https://iparhino.com/ -

- Spotify++
-  Deezer++
- Kodi from https://iosninja.io/ipa-library/download-kodi-18-ipa-leia-ios-iphone-ipad
The ALTStore application either crashes/ displays the Application is invalid, I am presently running  into the error where it says I need to disable offloading apps in the Itunes section of setting (which is disabled already)

**Comment by noah978** [comment]
@reach4bawer I've found that not all IPAs like that work with AltStore related to a certain issue that will hopefully be fixed in a future update. For now, I have working IPAs on my AltStore Source which you can browse from [here.](https://altsource.by.lao.sb/browse/?source=https%3A%2F%2Fbit.ly%2Fquarksource-plus)

However, there are no working Kodi IPAs for AltStore at the moment.
