### ISSUE TITLE
AltDaemon issue

### ISSUE THREAD

**Issue by draizoldev** [rileytestut/AltStore#259]
![F27F46DF-E40D-4A4E-8D0A-2D6309E1BC7C](https://user-images.githubusercontent.com/60373116/84318987-f2baae80-ab77-11ea-9407-2326ee67dc17.png)

Keep getting this error when trying out AltDaemon signing on my device. Whats the issue?

**Comment by brennanleblanc0** [comment]
That is a currently known issue. It is not currently know causing and seems mostly spontaneous. It seems to be caused by something locking /var/MobileData/ProvisioningProfiles, but not unlocking afterwards. I would try this mini write-up I did: If you’re having the “Operation not permitted” error, try installing “NewTerm (iOS 10-13)", then install the package “file-cmds”, then try running the command chflags nouchg /var/MobileDevice/ProvisioningProfiles, then run chflags nouchg /var/MobileDevice/ProvisioningProfiles/*, then try refreshing with AltStore again.
