### ISSUE TITLE
Run altserver on an device without itunes

### ISSUE THREAD

**Issue by fennectech** [rileytestut/AltStore#30]
The idea for this is to transfer the configuration of altserver from the machine that was used to install it to a device incompatible with iTunes (IE a device running with wine)  I have been getting "could not find altserver" tho   Is this because iTunes isn't installed?  if so is there a way I can trick the app into running without it? I just want to have altserver on my box that's always on (which happens to be a Linux box)  the software seems to run without a hitch but I haven't managed to connect.   Is anyone willing to help me?

**Comment by noah978** [comment]
AltServer requires iTunes to communicate with iOS devices because it requires something called "Anisette data" that (so far) can only be found through iTunes.

You could try and use Wine to run iTunes on Linux at the same time as AltServer, but I can't see it likely working. For now, AltServer without iTunes is impossible, so I will be closing this issue.
