### ISSUE TITLE
how does one use AltStore without Mail.app?

### ISSUE THREAD

**Issue by wizzard0** [rileytestut/AltStore#316]
My Apple Developer ID is linked to ProtonMail account, and to my knowledge, ProtonMail cannot be used with Mail.app (which would defeat ProtonMail security anyway).

Now, AltStore insists I install Mail.app plugin, and I presume it wants to retrieve incoming emails from Apple, which it won't have.

Is there a way to use AltStore without Apple Mail? E.g. copy-paste email content, etc?

Thanks in advance

**Comment by jimmyshadow1** [comment]
The mail plugin doesn't read any emails from anyone. The mail plugin is used to authenticate your Apple ID so that AltServer can install apps. To my knowledge you don't even need to log into the mail app. Just add the plugin and AltServer should work. But if you do then you can just use a throwaway Apple ID with AltStore.

**Comment by noah978** [comment]
As previously stated, the AltStore Mail Plugin does not read or search through any of your mail. It simply uses the plugin to gain access to the required Anisette data which is needed to create a signing certificate.
