### ISSUE TITLE
must be ios 12.2 ?

### ISSUE THREAD

**Issue by open9527** [rileytestut/AltStore#32]
must be ios 12.2 ?

**Comment by fennectech** [comment]
No  works on 13.1.1

**Comment by harper-coding-stuff** [comment]
I was able to get AltStore on iOS 13.1.2

**Comment by Redemption198** [comment]
iOS 12.2 or higher

**Comment by noah978** [comment]
As written by others, AltStore only works on iOS 12.2 and higher. This is because

1. It requires iOS 12+ libraries to work
2. Swift frameworks were finally built into iOS starting with 12.2. Supporting versions between 12.0 and 12.2 would drastically increase the app size since it would have to include the swift frameworks.

Closing this issue as it has been fully answered.

**Comment by Cottonwoodhill** [comment]
What about people like me who would like to jailbreak an iPhone running on iOS 10.3.4 (H3lix RC6) ? The Altstore solution can't be used as it only supports iOS from 12. Any advice on how to solve that ? 
Thanks in advance
