### ISSUE TITLE
Unable to find a provisioning profile

### ISSUE THREAD

**Issue by rbits0** [rileytestut/AltStore#376]
When I try to install AltStore onto my phone, the app appears, but my computer says "Could not find provisioning profile". I can open the app, and it will ask me if I want notifications, but then it will say "Unable to Launch Altstore"  "The file "Apps" couldn't be saved in the folder "Application Support""

**To Reproduce**
1. Delete AltStore
2. Install AltStore and enter Apple ID
3. Error message "Could not find provisioning profile"
4. Open app
5. Error message "The file "Apps" couldn't be saved in the folder "Application Support""

![Screenshot](https://user-images.githubusercontent.com/56014573/95537247-efa5d100-0a38-11eb-97e2-782eb09253c2.png)

 - OS: Windows
 - Version: 7

 - Device: iPhone 6 Plus
 - iOS: 12.4.7

**Additional context and logs**
Using AltServer 1.3.1 because later versions do not work on Windows 7. 1.3.1 worked before, but it's not working now. Also tried AltServer 1.2.2, also doesn't work

**Comment by jimmyshadow1** [comment]
Windows 7 isn't, and never has been, supported. Some people can get it to work, but it's hit or miss. Unfortunately since there's no support for that version, there's not a way that we can help you fix it. Windows 10 was a free update for multiple years, and I'm pretty sure it's still a free update. I would recommend updating.

**Comment by rbits0** [comment]
Windows 10 was only free for 1 year, when it first released. It is not free anymore, and costs $139 on Microsoft's website. I just don't know why AltServer suddenly stopped working. I'm going to have to update eventually. I guess I just can't sideload apps onto my phone until then.

**Comment by tvajjhala** [comment]
Same issue happening on Catalina. AltStore was working fine earlier

**Comment by jimmyshadow1** [comment]
@rbits0 that just isn't true. While it was advertised free for a year, it continues to be free now and it still works for people. Since you won't update I would recommend using a friends computer to install AltStore. An iCloud or iTunes update could've broken it, or a setting got changed in Windows itself. Like I said Windows 7 has never had official support, so we can't know what caused it to stop working.

**Comment by jimmyshadow1** [comment]
I would try having your phone forget trust with your computers, then retrusting it.

**Comment by NICOCuetoshki** [comment]
I have the same issue on a MacBook Pro and an iPhone 7

**Comment by NICOCuetoshki** [comment]
I found the solution. Re-download/update AltStore to fix this.

**Comment by rbits0** [comment]
I said at the start that I deleted AltStore and reinstalled it, and the problem was it didn't install. It's probably a different problem.

**Comment by Masoud-Studio** [comment]
hey @rbits0 
i have ur problem too!
at first i thnik it happend just for me, i see ur topic now i think the problem is "alt server"
first let check who can use alt server here? is any one here can use? whats ur configure? (OS? which alt server version u use? which iphone model? which iOS?)
my configure is:
win 7
alt server 1.3.1 (i try to install 1.4 and 1.3.3 but they dosen't work on win 7)
iphone 6
ios 12.4.8

**Comment by Masoud-Studio** [comment]
@rbits0 after one day finally i found the sulotion!
at first download AltServer 1.4
uninstall the old version
Install AltServer 1.4
when u run 1.4 it have error! its not match with win7!
for solve this issue watch this video: https://www.youtube.com/watch?v=_JTp0yPliJw

now i install AltStore on my iphone without any problem.

**Comment by rbits0** [comment]
Hey cool, it works. Seeing as it's such an easy fix, couldn't @rileytestut do this in the actual release, so people on windows 7 don't have to do this. Should be really easy.

**Comment by rogerluan** [comment]
Solved it by installing latest version of AltServer (v1.4) from https://altstore.io and retrying.
macOS 10.15.6, iOS 13.5

**Comment by ConnorHanks** [comment]
Uninstall Altstore and re-install from http://altstore.io.

**Comment by alvin9909** [comment]
I fixed it! I install it from a MacBook Air With MacOS Big Sur 11.1, and my iPhone on iOS 14.2 . Got the same message and this worked for me:

Go into mail>Settings>Button at the bottom of the window. Something with Manage Filter idk.> Enable AltPlugin.mailbundle

My computer is on Swedish so the Settings are not on English so I don't really know what the steps are in English.

**Comment by apivovarov** [comment]
Mar 20, 2023
(3017) There is no provisioning profile with the requested identifier on this team.
AltStore.AppleDeveloperError
If you are seeing this error, it's likely due to a recent server-side change made by Apple. Please see the following announcement with more info: https://twitter.com/altstoreio/status/1637953768728801282?s=20
