### ISSUE TITLE
Altstore App Continuosly Crashes

### ISSUE THREAD

**Issue by victorave97** [rileytestut/AltStore#391]
Altstore keeps crashing, I've deleted the app and re-downloaded several times and it doesn't help. Ive gone through and then deleted altserver and re-downloaded directly from the site again then proceeded to delete and re-download the app and still nothing. The altserver notification tells me that the app downloaded successfully but when i try to open it the apps immediately crashes exactly like what happens when it gets revoked after 7 days.I've been using altserver for around 4 months now and have had no issues until now.I've read through other posts and none have helped that i have found. Any help?

Mac OS
Catalina 10.15.6

Iphone 11
IOS 13.3.1

Uncover Jailbreak

**Comment by victorave97** [comment]
another question is if i update to ios 14 will i still be able to jailbreak? if thats the easiest route than i'll go with that

**Comment by jimmyshadow1** [comment]
Before you open a new issue, read previous posts and actually look at the answers. I have answered this at least 3 times at this point. AltStore 1.4+ will no longer work on iOS 13.3.1 due to a bug on that iOS version. You can either revert back to AltStore 1.3.6, or update to iOS 14. You will not be able to jailbreak iOS 14.

**Comment by BenSova** [comment]
@victorave97 Uncover does not support iOS 14. The only one that has support is checkra1n.

**Comment by victorave97** [comment]
@jimmyshadow1 if i upgrade to 13.5 will altstore then work?
