### ISSUE TITLE
Where are the apps?

### ISSUE THREAD

**Issue by mapleroyal** [rileytestut/AltStore#46]
Am I missing something?

I thought the whole point was that this would be a place where devs could post apps and users could find them. I can only see 2 apps—Delta and Delta Lite—and some devs are commenting here trying to figure out how to get their apps listed: https://github.com/rileytestut/AltStore/issues/11

**Comment by dlevi309** [comment]
> Am I missing something?
> 
> I thought the whole point was that this would be a place where devs could post apps and users could find them. I can only see 2 apps—Delta and Delta Lite—and some devs are commenting here trying to figure out how to get their apps listed: https://github.com/rileytestut/AltStore/issues/11

Give him a break.. for what’s been released, this is incredible for what you’re expecting. If it helps your question this is like, what, the second week it’s been out? I’d consider it beta, but him making it open source (which Riley /definitely/ didn’t have to do) does create the opportunity for services like ignition, tweakbox, etc. to release their own variations which will prob include all the ++ apps you’re after.

**Comment by git200iq** [comment]
How is it not perfectly reasonable to expect now that it’s officially released and specifically marketed as an alternative App Store, for it to have apps? It’s essentially a portal to a gameboy emulator and devs can’t even find out how to list their apps.

I don’t care about an emulator I was promised an alternative App Store. This has been in development for a LONG time and, as you noted, has actually been properly released for weeks already.

So...where are the apps? I’m not angry, but it’s a totally valid question.

**Comment by dlevi309** [comment]
> How is it not perfectly reasonable to expect now that it’s officially released and specifically marketed as an alternative App Store, for it to have apps? It’s essentially a portal to a gameboy emulator and devs can’t even find out how to list their apps.
> 
> I don’t care about an emulator I was promised an alternative App Store. This has been in development for a LONG time and, as you noted, has actually been properly released for weeks already.
> 
> So...where are the apps? I’m not angry, but it’s a totally valid question.

No, I get it, and I didn’t mean to come off as passive aggressive or anything :p I understand the point, but really this is the way I see it, since this is all released to the public you will definitely see lots of projects derived from this, along with official updates on this as well. If I were you, I’d regard the public release more as a public beta release, these waters haven’t really been tested in a long time (and especially not like this). Also, you should consider that the main priority right now is building a stable package/app manager. A concept I’ve imagined that would be cool to see is a repository-type resource similar to cydia, where developers could create their own repos along with push out their own apps.

**Comment by TheManchineel** [comment]
Yes, and I think this should be all the more reason for AltStore to have _more than one_ app, considering the amount of work that went into finding a trick that lets users have more than 3 apps sideloaded and signed. Such a unique feature doesn't get showcased at all this way.

**Comment by noah978** [comment]
This is possible using AltStore Sources which is currently in the Patreon Beta. If you'd like to learn more about how to create an AltStore Source, [see here.](https://noah978.github.io/AltStore-Docs/Sources)

Closing this issue.
