### ISSUE TITLE
Install AltStore with Windows Store iCloud?

### ISSUE THREAD

**Issue by TheConfax** [rileytestut/AltStore#563]
Not everyone knows that iCloud from Windows Store is version 11.5, while the one from Apple website is version 7.21.
They are basically two different programs and the one from Apple website has (very) reduced functionality and unfixed security issues.

Regular users should not perform downgrade just for AltStore, is there any technical workaround?

**Comment by greenish-guy-tech-1-h33aha-777555378477** [comment]
your f̸k̸n̸g̸ ժմʍҍ, ℵ❡ᾰ, so stop вƈђἷᾗʛ and 𝒈̲̅𝒆̲̅𝒕̲̅ 𝒂̲̅ 𝒍̲̅𝒊̲̅𝒇̲̅𝒆̲̅, ἿḋἿὄҭ!

**Comment by TheConfax** [comment]
@greenish-guy-tech-1-h33aha-777555378477 never expected to find retarded people on GitHub, I need to change my expectations.

Any response tho?

**Comment by GetThatGuyOverThereIn10293** [comment]
You should actually g̲o̲ g̲e̲t̲ a̲ f̲k̲n̲ l̲i̲f̲e̲, and ƳƠƲ ƝƓƛ ƧӇƠƲԼƊ ƊƖЄ

**Comment by GetThatGuyOverThereIn10293** [comment]
and if anyone gets a d!sl.ike, then he is 𝕥𝕙𝕖 𝕘𝕒𝕪𝕖𝕤𝕥 𝕗𝕜𝕟 𝕟𝕘𝕒

**Comment by noah978** [comment]
Unfortunately, MSFT store apps are obfuscated in a way that makes it near impossible for an application like AltServer to get the information it needs. Which is why we require the normally installed version where the iCloud files needed to generate Anisette data can be easily accessed.

While it might be *possible* to use the MSFT store version, it would require a great deal more effort than the benefit it would generate. In the future, there is a high chance AltStore signing logic may have to be rewritten to a method that doesn't require iCloud in the first place. We also don't require you to *use* the installed iCloud but we do need it installed.

**Comment by TheConfax** [comment]
> We also don't require you to _use_ the installed iCloud but we do need it installed.

Well, if I have installed the Windows Store version of iCloud, the installer prevents me to install the older 7.21 one, I think that your logic is completely flawed, soon that version won't be supported anymore and Windows support made in this way is basically nonexistent for everyone who uses iCloud for Windows regularly.

**Comment by DarthAV** [comment]
@TheConfax 
Check out this reddit thread that gives the steps to install AltStore and use windows store iCloud at the same time.

https://www.reddit.com/r/jailbreak/comments/rp5buz/tutorial_how_to_use_altserver_if_you_have_to_use/
>Altstore only supports the iCloud you download from the Apple website. But you may have to use the windows store version, for example to use the "iCloud Passwords" extension for Chrome.
> 1. Install iTunes and iCloud from Apple website.
> 2. Copy the "Apple Application Support" and "Internet Services" folders from C:\Program Files (x86)\Common Files\Apple
> 3. Create a seperate folder for them somewhere else. Paste them in.
> 4. Remove iCloud but keep iTunes. Install iCloud from the windows store.
> 5. Install altserver. When you open it the first time, click on "choose folder", and choose the one you created in the 3rd step.

I can verify that this method allowed me to use windows store icloud and sign Altstore apps...
Could the devs verify if this is something that could work long term _(does the data expire?)_ and if so maybe even add it to official documentation.

**Comment by frissle** [comment]
> @TheConfax Check out this reddit thread that gives the steps to install AltStore and use windows store iCloud at the same time.
> 
> https://www.reddit.com/r/jailbreak/comments/rp5buz/tutorial_how_to_use_altserver_if_you_have_to_use/
> 
> > Altstore only supports the iCloud you download from the Apple website. But you may have to use the windows store version, for example to use the "iCloud Passwords" extension for Chrome.
> > 
> > 1. Install iTunes and iCloud from Apple website.
> > 2. Copy the "Apple Application Support" and "Internet Services" folders from C:\Program Files (x86)\Common Files\Apple
> > 3. Create a seperate folder for them somewhere else. Paste them in.
> > 4. Remove iCloud but keep iTunes. Install iCloud from the windows store.
> > 5. Install altserver. When you open it the first time, click on "choose folder", and choose the one you created in the 3rd step.
> 
> I can verify that this method allowed me to use windows store icloud and sign Altstore apps... Could the devs verify if this is something that could work long term _(does the data expire?)_ and if so maybe even add it to official documentation.

I can verify that this method will also work with Sidestore

**Comment by Tommy2678** [comment]
Doesn't work for me. I don't even have iCloud. But I just cannot get this program to recognize that I have itunes installed. Maybe it's because I had apple music?

I had issues earlier when I tried to install an older version of itunes to restore an iPod I had. After I tried that, nothing would connect. Looks like that issue is messing me up here. I can't factory reset my computer at the moment. How do I fix this? I've already deleted the itunes and all the apple appps, individually removed the apple folder from programfiles-commonfiles, etc. Cannot under any circumstances get my phone to connect.
