### ISSUE TITLE
[Feature request] Enable JIT for jailbroken A11 devices

### ISSUE THREAD

**Issue by Nixuge** [rileytestut/AltStore#576]
Could it be possible to do it? I know it's possible if you install an app from cydia, but idk if you sideload. This request is mainly for the NDS on delta since melonds is pretty slow

**Comment by nyuszika7h** [comment]
I don't think AltStore has the ability to do this right now, since the main purpose is to install real signed apps that work even when not in jailbroken state. The only way to get true dynamic-codesigning entitlement is if you're Apple or if you fakesign the app with a jailbreak. If you get it from https://apps.altstore.io/ and then sideload with Filza and AppSync Unified, that might work.

**Comment by noah978** [comment]
AltStore is not designed for sideloading things that are specific to jailbroken users, that is better suited to existing stores like Cydia. As for getting JIT in Delta to work on A11 devices, that is best suited here: https://github.com/rileytestut/Delta/issues/new
