### ISSUE TITLE
I dont know how to explain what this is, so I sent an image of this. Someone please help. 

### ISSUE THREAD

**Issue by Fireblade696** [rileytestut/AltStore#660]
![Screenshot (136)](https://user-images.githubusercontent.com/66755843/106374371-8f6ccf00-6348-11eb-88f5-e2cc260008eb.png)
 Please explain this and help me

**Comment by veritas06** [comment]
This doesn't look like an AltStore/AltServer error. When searching for that message i found other posts about it for Cydia Extender & the suggestion seemed to be using a "burner" Apple ID. I did find one post that said to visit https://developer.apple.com/, sign in with that ID, & see if there are terms & conditions to accept.

Also found this: "This is because your account is: -> part of a family (under 13), -> or using a app specific password."
