### ISSUE TITLE
Runtime error after self-compilation (Domain=NSPOSIXErrorDomain Code=22 "Invalid argument")

### ISSUE THREAD

**Issue by sy6sy2** [rileytestut/AltStore#749]
Hi,

I am trying to compile and run AltStore from Xcode. Compilation is ok, AltStore is installed by Xcode on my device but I get an error on launch: "Unable to Launch AltStore, The file "Apps" couldn't be saved in the folder "Application Support"".

Thank you for the help!

```
Failed to migrate database to app group: Error Domain=NSCocoaErrorDomain Code=512 "The file “Apps” couldn’t be saved in the folder “Application Support”."
UserInfo={NSFileOriginalItemLocationKey=file:///var/mobile/Containers/Data/Application/9EA53DE1-3D2A-4C99-9771-873744F1F359/Library/Application%20Support/Apps/,
NSURL=file:///var/mobile/Containers/Data/Application/9EA53DE1-3D2A-4C99-9771-873744F1F359/Library/Application%20Support/Apps/,
NSFileNewItemLocationKey=file:///var/mobile/Containers/Data/Application/9EA53DE1-3D2A-4C99-9771-873744F1F359/Library/Application%20Support/Apps/, NSUnderlyingError=0x283dda700 {Error
Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSURL=file:///var/mobile/Containers/Data/Application/9EA53DE1-3D2A-4C99-9771-873744F1F359/Library/Application%20Support/Apps/}}}
```

* Xcode 12.4
* Free dev account
* iPhone 7 iOS 14.2
* macOS 11.2.3

**Comment by jkcoxson** [comment]
Did you ever solve this?

**Comment by 0x1af2aec8f957** [comment]
This problem still exists.

**Comment by mahee96** [comment]
was this ever fixed? 

Having the same issue when running forked project "sidestore" which uses same codebase from altstore. 

https://github.com/altstoreio/AltStore/blob/5a0f2de77e0723bf782447edbc0ab2bc11688234/AltStoreCore/Model/DatabaseManager.swift#L492  
  
  
![image](https://github.com/user-attachments/assets/87591e32-7437-4c68-9ea3-f3a33799d3cf)

**Comment by mahee96** [comment]
@jkcoxson, @shanegillio can someone confirm and re-open if this issue is still not covered/resolved ? 

FYI, Tested on iPhone 14 Pro 256G Device, iOS Simulator 15.2, 16.2, 18.0.
Even the simulator filesystem backed by Mac is having this error (during startup), seems to stem from trying to replace dir with itself?

**Comment by mahee96** [comment]
A check to confirm if tgt != src should fix probably

![image](https://github.com/user-attachments/assets/25cb69d9-033e-4f7b-9eee-9a4d5ab66596)

**Comment by ahmedelmoughazy** [comment]
Just comment the line mentioned in https://github.com/altstoreio/AltStore/issues/749#issuecomment-2422739146, and run, I assume this line is there to migrate the previously installed version of Altstore to the newly version, comment it if you are running the app for the first time, then uncomment it and run it again, it will work. I think the problem is that `previousAppsDirectoryURL` didn't exist before. that worked for me.
