### ISSUE TITLE
AltStore is not support Microsoft Store iCloud. 

### ISSUE THREAD

**Issue by imlyzh** [rileytestut/AltStore#770]
Icloud can only be selected under administrator privileges.
After selecting the app store, it will not work during installation

**Comment by TheElectroclassics** [comment]
It clearly states in the FAQ that you need the Apple version, not the Microsoft Store one.
https://altstore.io/faq/

**Comment by imlyzh** [comment]
> It clearly states in the FAQ that you need the Apple version, not the Microsoft Store one.
> 
> https://altstore.io/faq/

but…
I cannot install icloud provided by Apple on my computer

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/rileytestut/AltStore/issues/770#issuecomment-867941197

Although it may state such, the version that is not distributed via the Microsoft Store is lacking some important improvements that the version that is distruibuted via the Microsoft Store has. Also, for many devices, the former version is the only version that is available. Therefore, perhaps this should be treated as a feature request for support the former version, regardless of its feasibility.

**Comment by sleeping-player** [comment]
> [http://github.com/rileytestut/AltStore/issues/770#issuecomment-867941197](https://github.com/rileytestut/AltStore/issues/770#issuecomment-867941197)
> 
> Although it may state such, the version that is not distributed via the Microsoft Store is lacking some important improvements that the version that is distruibuted via the Microsoft Store has. Also, for many devices, the former version is the only version that is available. Therefore, perhaps this should be treated as a feature request for support the former version.

Yes. iCloud for Microsoft Store will soon provide access to the iCloud Photos library from the Microsoft Photos app. This is not possible in the iCloud legacy version.
I am looking for a way to install the latest version of iCloud to use this function, and for this, I am looking for a way to run AltServer in Docker. (Personally, I am having difficulties because my device running Docker is Synology, and the libimobiledevice port is not available here.) However, this is a special method, and ordinary people will not be able to use this workaround.
If AltServer continues to require a legacy version of iCloud, they won't be able to take advantage of the new features iCloud provides for Windows.

**Comment by imlyzh** [comment]
I successfully used the icloud provided by apple. I need to be careful to install it in the Program Files(x86) directory. If there is no other purpose, maybe I should close this issue?

**Comment by imlyzh** [comment]
Thank you very much for your help.

**Comment by sleeping-player** [comment]
> I successfully used the icloud provided by apple. I need to be careful to install it in the Program Files(x86) directory. If there is no other purpose, maybe I should close this issue?

Is it possible to install the Microsoft Store version and the legacy version on the same device?

**Comment by imlyzh** [comment]
I installed Windows store icloud, and the altserver is still running normally.
